version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/microservice
file_exists_behavior: OVERWRITE
hooks:
  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/copy.sh
      timeout: 300
      runas: root        
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
