version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - cd ./auth && sudo npm init
      - cd ../gateway && sudo npm init
  build:
    commands:
      - echo Build started on `date`
      - cd ./auth && npm install
      - cd ../gateway && npm install
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - appspec.yml
    - script/
    - '**/*'
